### ISSUE TITLE
Needs a better name.

### ISSUE THREAD

**Issue by p4plus2** [JackTheSpades/SpriteToolSuperDelux#1]
Oh yeah and 
	"* shared routines. This one was 99% stolen, er I mean borrowed from p4plus2's GPS."
And a large chunk of program logic :P.  But it proves my point, I told y'all that GPS could be modified into a sprite tool relatively easily.

I propose the name: KoopaMushroomSkewers

**Comment by Alcaro** [comment]
wait, not [Beaver Nacho Casserole](http://smwc.me/1219760)?
