### ISSUE TITLE
Can custom sprites be inserted to E0-FF?

### ISSUE THREAD

**Issue by kyeon-go** [JackTheSpades/SpriteToolSuperDelux#108]
According to readme, D0-FF is the generator section. So I inserted same generator to DF, EE and DF one works but EE one doesn't..

Hmm... PIXI says "All sprites applied successfully!", but can't Lunar Magic handle it properly?

**Comment by Atari2** [comment]
It looks like the README is spearing misinformation, generators are D0-DF, as evidenced by this line of code branching away to .NotGen if sprite number is $E0 or upper. <https://github.com/JackTheSpades/SpriteToolSuperDelux/blob/e7443f2880b8c56777cc6e75b7b7722934d4933d/asm/main.asm#L802-L803>
I will update the README to say that the range is D0-DF
