### ISSUE TITLE
[FEATURE REQUEST] Variation of SpawnMinorExtended which keeps spawning the sprite.

### ISSUE THREAD

**Issue by MarioFanGamer** [JackTheSpades/SpriteToolSuperDelux#111]
Some minor extended sprites are spawned such that instead of failing to spawn the sprite altogether, they override older slots and there are quite a few such minor extended sprites which use it (cracked shell piece, block debris, Boo Stream trail, glitter, to be more precise) and I feel like it's common enough to warrant a routine to be included for PIXI.

A custom sprite which easily hits the limit is the [Coin Stream](https://www.smwcentral.net/?p=section&a=details&id=35149), a derivate of the Boo Steam which suffers from using the existing routine.

If you place three onscreen, neither of them will spawn the coins properly because they easily fill up all the minor extended sprite slots, leaving gaps in the trail:
![CoinStream](https://github.com/JackTheSpades/SpriteToolSuperDelux/assets/48353884/2d83c099-090a-4950-8dbe-a93b7fe823fc)

In contrast, the vanilla Boo Stream leaves its trail much more naturally in which the oldest Boo disappears instead of having gaps in the stream:
![BooStream](https://github.com/JackTheSpades/SpriteToolSuperDelux/assets/48353884/2b586763-9315-43da-847f-092627df4e64)

This technically also affects smoke and regular sprites but the former is only used by Torpedo Teds and when turning around (separately, as it turns out), the latter when spawning a sprite from the item box or a block (incidentally one of the few times where SMW even searches for all sprite slots).

I know the creator could also change the sprite to it into account but that would mean opting for a non-shared routine and there are other use cases where this feature is handy (like my block debris disassembly), I think this one warrants a reason to be routine included for PIXI.

**Comment by Atari2** [comment]
Does it override the oldest slot of the same sprite ID or any slot regardless of the sprite ID?

**Comment by MarioFanGamer** [comment]
The way the system works is that the oldest slot is overwritten independently of the spawner thanks to using only one global variable ([$185D](https://smwc.me/m/smw/ram/7E185D)).

**Comment by Atari2** [comment]
Please check if the routine that I added fixes the problem @MarioFanGamer
