### ISSUE TITLE
Sprites not inserted due to routines

### ISSUE THREAD

**Issue by linkure134** [JackTheSpades/SpriteToolSuperDelux#113]
When I insert the sprites, it gives me the error provided in the screenshot.

Desktop/modding/#dlc/+tools/pixi_v1.42/routines

Files are in screenshot

It should insert everything like normal correctly unless directories were moved.

![sprtool1 42_error](https://github.com/JackTheSpades/SpriteToolSuperDelux/assets/169564307/5f44edbf-0479-4e9f-bc44-bd1a54f6ac8a)

I moved the routines folder from 1.40 to 1.42 without replacing the important files and I still get this error/bug.

**Comment by Atari2** [comment]
This is not a bug, the routines were moved from all being in one giant folder with 1000 files to being divided into subfolders in the pixi 1.32->1.40 switch, thus by copying over from an old version you effectively duplicated all of the ones that were moved. Don't copy folders between pixi versions, move just the required files and not the provided routines.
