### ISSUE TITLE
pixi using full path names, taging folder starting with "!" as a define.

### ISSUE THREAD

**Issue by TRNB42** [JackTheSpades/SpriteToolSuperDelux#16]
Inserting sprites from a folder starting with an exclamation point creates an error were pixi tries to read the folder name as a define.
![pixi_error](https://user-images.githubusercontent.com/58887035/70851915-4f9b0d80-1e50-11ea-9a9b-f59a84771105.PNG)

Using asar directly to insert patches does not pull this same error.

**Comment by Atari2** [comment]
This is not a pixi problem, it's an asar (https://github.com/RPGHacker/asar) problem.
