### ISSUE TITLE
-ssc command line option doesn't work

### ISSUE THREAD

**Issue by ShinyNinetalesTM** [JackTheSpades/SpriteToolSuperDelux#18]
Tattletale said that it apparently wasn't implemented, and he tell me to create an issue so here it is.

The option isn't working, for both normal and custom sprites. If somebody can test it for providing more feedback would be good.

I'm not sure if **-mwt** or **-mw2** are working properly as well (as I don't care about them), but according to my testing, at least **-s16** is working fine.

**Comment by tattletalelap** [comment]
Resolved in 1.2.14.

**Comment by ShinyNinetalesTM** [comment]
based
