### ISSUE TITLE
Malfunctions when disabling VRAM Patch in Lunar Magic.

### ISSUE THREAD

**Issue by lion65816** [JackTheSpades/SpriteToolSuperDelux#21]
Just a thing I've come across and bothered Tattletale about over the past few days.

Using PIXI without the VRAM Patch will make custom sprites go on a fritz, from relying on GetDrawInfo to always be ran to display properly to SubOffScreen not functioning correctly (sprites vanish and despawn completely at the very border of the screen instead of being available during a certain range for smooth despawning and respawning).

This is due to PIXI and other tools relying on LM's large levels feature being inserted, which in turn relies on the VRAM Patch.

Please be wary orz

**Comment by Atari2** [comment]
Added a warning about this in #27
