### ISSUE TITLE
Sprite conversion problem

### ISSUE THREAD

**Issue by Rykon-V73** [JackTheSpades/SpriteToolSuperDelux#24]
For the most part, converting any sprite to .json is fine, but for an example if you make any 32x32 sprite use tiles 000, 001, 010 and 011 or $00,$02,$10 and $12, then after conversion view it in LM editor, the bottom part of the sprite will look screwed up. Just telling you about this. I think tiles $00,$01,$20,$22 from SP1 and SP3 have this issue. A fix might be nice.

**Comment by Atari2** [comment]
I haven't done much testing on this but could you please provide some files or screenshots describing the issue more in detail? It's kinda hard to guess with the level of description you gave here.
Until further info will be given I'll label this as invalid, as this doesn't seem to be a Pixi related issue.

**Comment by Rykon-V73** [comment]
Here's the proof.At the first picture, I inserted the tiles from the tilemap numbers.And at the 2nd screen when inserting in-editor, it looks screwed up.
    On Tuesday, July 28, 2020, 2:44:36 PM GMT+3, Alessio <notifications@github.com> wrote:  
 
 


I haven't done much testing on this but could you please provide some files or screenshots describing the issue more in detail? It's kinda hard to guess with the level of description you gave here.
Until further info will be given I'll label this as invalid, as this doesn't seem to be a Pixi related issue.

**Comment by Atari2** [comment]
> Here's the proof.At the first picture, I inserted the tiles from the tilemap numbers.And at the 2nd screen when inserting in-editor, it looks screwed up. 

Umm, I don't see any images?

**Comment by Rykon-V73** [comment]
Maybe these links should do:Imgur

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Imgur

Imgur

Post with 0 votes and 2 views.
 |

 |

 |

https://i.imgur.com/qQKMlAL.png


    On Wednesday, July 29, 2020, 9:09:23 PM GMT+3, Alessio <notifications@github.com> wrote:  
 
 



Here's the proof.At the first picture, I inserted the tiles from the tilemap numbers.And at the 2nd screen when inserting in-editor, it looks screwed up.


Umm, I don't see any images?
