### ISSUE TITLE
Add routines from GIEPY

### ISSUE THREAD

**Issue by kkevinm** [JackTheSpades/SpriteToolSuperDelux#25]
GIEPY has some useful routines that could be easily be converted and put into PIXI, for example SolidSprite, CapeContact, FireballContact, LoseYoshi.

**Comment by Atari2** [comment]
The routines have been converted and will be added to the next release of pixi.
New routines will be
`CapeContact`
`FireballContact`
`LoseYoshi`
`CheckForContactAlternate`
`SetPlayerClippingAlternate`
`SetSpriteClippingAlternate`
