### ISSUE TITLE
Potential issue with using nested shared routine calls

### ISSUE THREAD

**Issue by mellonpizza** [JackTheSpades/SpriteToolSuperDelux#28]
At the moment there appears to be the following issue when using nested shared routine calls in a particular way (This happens to be the way I discovered this):
-sprite.asm contains routines A and B, in that order.
-when assembling pixi finds these and notes they are the first implementations of them and does whatever it does to setup the initial macros.
-pixi then looks at routine A and discovers that it calls routine B within it, and my assumption is that it puts in a standard macro which fails because pixi has to do some extra work after assembling sprite.asm.
-In the end pixi reports (could not find label B (jsl B))
I'm not sure if this is too specific a bug to fix, either way I figure it's worth pointing out. Let me know if this doesn't reproduce the error and I can provide some files if needed.

**Comment by Atari2** [comment]
It would be really nice if you could provide the files needed to reproduce the error. I assume the routines are some that you wrote yourself cause currently in Pixi there are no routines that use nested calls within them.
Also the fact alone that Pixi supports nested routine calls is an accident, as I don't think it was supposed to work at all.

**Comment by Atari2** [comment]
Okay turns out that, for some really weird reason, if you patch the file created by pixi at runtime with asar's standalone executable (or python's dll binding, or even a cpp program created just to patch that file), the file will get applied correctly with absolutely 0 errors, while if you run Pixi, for some reason the bundled dll will fail.
I don't know why this is happening.

**Comment by Atari2** [comment]
Turns out it was an issue with namespaces, there is a fix that I have currently for it. I just need some testing and hopefully I'll push it once I'm sure it doesn't cause problems.

**Comment by Atari2** [comment]
Update: this will most likely be fixed when Asar 1.80 releases due to the addition of global labels.
