### ISSUE TITLE
-mw2 and -mwt not implemented

### ISSUE THREAD

**Issue by TheLX5** [JackTheSpades/SpriteToolSuperDelux#29]
They're not implemented according to the source in pixi.cpp.

It's just matter of treating both files like the .ssc one.

The .mw2 file requires a bit of extra handling, as the file provided via the -mw2 command may have a terminator byte (0xFF) which should be removed on the final .mw2 that PIXI outputs. 

If a .mw2 file is provided, the header byte (always 0x00) should be omitted when generating the data from the .json files.

From Lunar Magic's help file:
> As with the ROM data, the first byte of the file is the sprite data header (reserved, should be zero for this), and the file should end with a 0xFF byte.

**Comment by Atari2** [comment]
Fixed in latest update
