### ISSUE TITLE
Encoding error from data generated from .json files

### ISSUE THREAD

**Issue by TheLX5** [JackTheSpades/SpriteToolSuperDelux#30]
The description/tooltip and Custom Collection of Sprites list entry are treated as UTF-8 where Lunar Magic uses ANSI/Windows 1252 for its auxiliary files.
This ends up breaking some characters such as accent marks:
> Actúa
> ActÃºa

It's possible to workaround this by using .cfg files and a .ssc file, but it's still a bug with .json 
 sprites parsing.

**Comment by Atari2** [comment]
I don't want to deal with encoding shenanigans in C++, this is a very minor annoyance and will be dealt with at some point, but for now this is out of scope.

**Comment by Atari2** [comment]
This issue is further reinforced by the json external parser library, which relies on text being utf-8. This most likely won't be fixed.

**Comment by TheLX5** [comment]
It's no longer needed as Lunar Magic 3.30 requires auxiliary files use UTF-8.

> -the .msc, .dsc, .ssc, .sscov, .extmod, and usertoolbar.txt files
 must now use UTF-8.  Existing english text files are not affected,
 but other languages will need to change the encoding used for
 those files.

**Comment by Atari2** [comment]
As of LM3.30, this bug is no longer relevant, see comment above.
