### ISSUE TITLE
Feature request: Routines macro labels

### ISSUE THREAD

**Issue by GhbSmwc** [JackTheSpades/SpriteToolSuperDelux#32]
After moderation of my latest [screen scrolling pipes](https://www.smwcentral.net/?p=section&a=details&id=24957), I realized this:

“Upon moderation, the Pixi routine included didn't insert properly due to faulty label names, so I re-named them and updated the submission file. Quick fix, tested with the carriable triangle sprite.” - MiniMawile303

This would really help on avoiding potential leaking labels and at the same time, looks better.

In case you didn't know what is a macrolabel/macrosublabel it is this:
```
?MacroLabel

?.MacroSubLabel

?..MacroSubSubLabel
```

**Comment by Atari2** [comment]
You're free to submit a [PR](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-pull-requests) fixing this issue if you think it's significant enough. Even thought I feel like it should be up to the coder's responsibility to fix any conflicts between their resource and Pixi's routines.

**Comment by Atari2** [comment]
Closed with #47
