### ISSUE TITLE
Incompatible with AddmusicK

### ISSUE THREAD

**Issue by Flabort** [JackTheSpades/SpriteToolSuperDelux#4]
Background on this issue: Working with a group building a SMW hack together. Some of us are designing levels, some designing graphics, some doing both, we have a small group making the overworld and arranging the levels into this overworld, so it stands to reason we don't all have the same tools on our computers. The way we have organized ourselves, we have a group leader who is assembling the final project together, who's job is to make sure everything used is compatible. When something isn't compatible, IE two people used the same map16 area for different things, he organizes us to fix this mistake. For the most part, we have only had two incompatibility issues. One was the mentioned map16 - the reason we haven't had more of this is we declare beforehand which ranges we want, and the reason we had it at all was because one person's claim got lost in a tide of messages. The other is the reason we have decided to use Romi's Sprite Tool instead of PIXI.

So we tried to insert a sprite in a level using PIXI. On my machine and copy of our hack, it worked. I could insert the sprite, and use it in a level I was designing. This was fine. I distributed my level and the resources (sprites, exGFX, map16, etc) to our group for testing and integrating into the project. This is where we learned that our organizer and a select few members of our group could not use PIXI on their copy of our project. 

After testing on fresh unmodified ROM images, it was discovered that PIXI does work on their machine, but not on the project rom. Through testing the various patches and tools used in our rom, we narrowed the problem down. ROMs which have had music inserted by AddmusicK could not have sprites inserted by PIXI. The PIXI process would run, and then hang before completion. It was not a matter of time, as our organizer waited a whole day to see if it would complete. 

Here is an image of their debug log: https://cdn.discordapp.com/attachments/353786871131668480/356992886287368193/image.jpg

**Comment by tattletalelap** [comment]
Asar used to hang on pixi due to the sprite per level / freedata misalignment. Should be fixed by now after all this time.
