### ISSUE TITLE
Lists are searched in wrong filepaths relative to ROM

### ISSUE THREAD

**Issue by DiskPoppy** [JackTheSpades/SpriteToolSuperDelux#42]
When the ROM isn't directly in pixi folder, then it looks for the list in sort of an "opposite" path. Let me demonstrate:
```
$ ./pixi ../rom
Couldn't open list file pixi/list.txt for reading%
$ ./pixi test/rom
Couldn't open list file ../list.txt for reading%
```

**Comment by Atari2** [comment]
Care to say what version you're using?
On my end it works fine
```
D:\aless\Desktop\test_folders\pixi>pixi.exe ../test.smc
Could not open "D:/aless/Desktop/test_folders/list.txt"

D:\aless\Desktop\test_folders\shovda\pixi>pixi.exe test/test.smc
Could not open "D:/aless/Desktop/test_folders/pixi/test/list.txt"
```
Both of those lookups are correct, since list.txt needs to live alongside the rom (for some reason).

**Comment by DiskPoppy** [comment]
I was using 1.32, however with the latest build from the repo, it appears to be fixed.

**Comment by Atari2** [comment]
Just to be clear, I edited my reply to clarify that I'm encountering this issue even on 1.32

**Comment by DiskPoppy** [comment]
What's weird it's started working for me in 1.32 too, could be a bug that only manifests based on some unknown condition

**Comment by DiskPoppy** [comment]
Hmm, it happens only on 1.32 natively on mac, but I swear the windows build was broken too, but now the windows build works and mac build doesn't.

**Comment by DiskPoppy** [comment]
Anyway, it doesn't seem to happen on master at all, so should be ok
