### ISSUE TITLE
Updated routines, too lazy to create a PR

### ISSUE THREAD

**Issue by TheLX5** [JackTheSpades/SpriteToolSuperDelux#55]
I'm sure I said a long time ago that I had some fixes for the routines, but you (Atari) told me to wait until you pushed some changes about the C++ side to the master (?) branch and I'm not sure if that ever happened (pretty sure you were busy IRL, understandable tbh). I'm too lazy to set a PR so I'll just dump them here for the time being.

This doesn't address anything that Anas reported a while ago.

DL: [pixi.zip](https://github.com/JackTheSpades/SpriteToolSuperDelux/files/7834204/pixi.zip)

**Comment by Atari2** [comment]
@TheLX5 why is the BounceChangeMap16.asm routine completely nuked?

**Comment by TheLX5** [comment]
It seems that BounceChangeMap16.asm got replaced by BounceSetupMap16.asm, but I forgot to remove the former from the zip.
Apparently was more intuitive to call a helper routine to setup things and then call either $00BEB0 or %ChangeMap16(), as a bonus this made completely irrelevant the portion that hijacked the original $00BEB0 routine from the original Custom Bounce Blocks patch, leaving said routine intact and less prone to bug reports outside of PIXI's scope.

Also the PR seems good to me.

**Comment by Atari2** [comment]
So wait, I can just nuke BounceChangeMap16.asm completely? Doesn't need to exist at all?

**Comment by TheLX5** [comment]
Exactly.

**Comment by Atari2** [comment]
Merged #56
