### ISSUE TITLE
Sprite loader corrupts extra byte pointers on SA-1 ROMs

### ISSUE THREAD

**Issue by TheLX5** [JackTheSpades/SpriteToolSuperDelux#70]
SA-1 uses 16-bit XY for these routines:
https://github.com/JackTheSpades/SpriteToolSuperDelux/blob/master/asm/main.asm#L494
https://github.com/JackTheSpades/SpriteToolSuperDelux/blob/master/asm/main.asm#L749
https://github.com/JackTheSpades/SpriteToolSuperDelux/blob/master/asm/main.asm#L894

This means that in cases such as `Y = $00FE` where `Y` ends up being `$0101` after the `INY #3`, the routine will only read `Y` as  `$0001` and corrupting extra byte data in the process. This issue can only be found when you use lots of sprites with high extra byte count on each, I assume this is why nobody has reported this before...

I'd open a pull request, but I'm lazy. This basically fixes the issue on the three routines:

```
    REP #$20
    INY #3
    TYA
    CLC
    ADC $CE
    SEP #$20
    STA !extra_byte_1,x
    XBA
    STA !extra_byte_2,x
    LDA $D0
    STA !extra_byte_3,x
```

Bank crossing is ommited... I don't think it's worth having it here as I don't think this data can cross banks at all  anyway.

**Comment by Atari2** [comment]
Are you sure that SA-1 uses 16-bit XY?
Here at https://github.com/JackTheSpades/SpriteToolSuperDelux/blob/master/asm/main.asm#L457-L466
I see that we do REP-SEP, so wouldn't that mean that XY is 8 bit there anyway?
